import { Abi } from "viem";

// The ABI for the SealEncrypt contract
export const SEAL_ENCRYPT_ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AlreadyAdmin", type: "error" },
  { inputs: [], name: "InvalidDocument", type: "error" },
  { inputs: [], name: "NotAdmin", type: "error" },
  { inputs: [], name: "NotAnAdmin", type: "error" },
  { inputs: [], name: "NotOwner", type: "error" },
  { inputs: [], name: "UsernameCannotBeEmpty", type: "error" },
  { inputs: [], name: "UsernameTaken", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "string", name: "cid", type: "string" },
      {
        indexed: false,
        internalType: "string",
        name: "Revokeuser",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "RevokeAddr",
        type: "address",
      },
    ],
    name: "AccessRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "AdminAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "AdminRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "addedBy",
        type: "string",
      },
      { indexed: false, internalType: "string", name: "cid", type: "string" },
      { indexed: true, internalType: "address", name: "user", type: "address" },
    ],
    name: "DocumentAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "string", name: "cid", type: "string" },
      {
        indexed: false,
        internalType: "string",
        name: "shareUser",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "shareAddr",
        type: "address",
      },
    ],
    name: "ShareAccess",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "username",
        type: "string",
      },
    ],
    name: "UsernameSetAndCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "string",
        name: "username",
        type: "string",
      },
    ],
    name: "UsernameSetAndUpdated",
    type: "event",
  },
  {
    inputs: [{ internalType: "address", name: "_admin", type: "address" }],
    name: "addAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "string", name: "cid", type: "string" },
      { internalType: "uint256", name: "unlockTime", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "address[]", name: "recipients", type: "address[]" },
      { internalType: "bool", name: "encrypted", type: "bool" },
      { internalType: "string", name: "filename", type: "string" },
    ],
    name: "addDocument",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "getDocument",
    outputs: [
      {
        components: [
          { internalType: "string", name: "docName", type: "string" },
          { internalType: "string", name: "cid", type: "string" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "unlockTime", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "bool", name: "encrypted", type: "bool" },
          {
            internalType: "address[]",
            name: "sharedRecipients",
            type: "address[]",
          },
        ],
        internalType: "struct SealEncrypt.Document",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getDocumentCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "isAdmin",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_admin", type: "address" }],
    name: "removeAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "documentId", type: "uint256" },
      { internalType: "address", name: "revokeAdd", type: "address" },
    ],
    name: "revokeDocumentAccess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "username", type: "string" }],
    name: "setUsername",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "documentId", type: "uint256" },
      { internalType: "address", name: "recipient", type: "address" },
    ],
    name: "shareDocumentAccess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "usernameToAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "usernames",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
] as const satisfies Abi; // Use `as const satisfies Abi` for viem's type inference
